### ISSUE TITLE
When running Scalatra tests, NPE is thrown due to url method in layout templates

### ISSUE THREAD

**Issue by seratch** [scalatra/scalatra#368]
When using `url` method (e.g. `url(Controller.someScalatraRerverseRouteURL)`) in `src/main/webapp/WEB-INF/layouts/default.jade`, NPE is thrown only when running Scalatra tests. 

After removing `url` method from default.jade, everything goes fine. Basically we shouldn't use `url` method?

```
java.lang.NullPointerException: null
        at org.scalatra.servlet.ServletBase$$anon$1.context(ServletBase.scala:26) ~[scalatra_2.10-2.2.2.jar:2.2.2]
        at org.scalatra.ScalatraBase$class.servletContext(ScalatraBase.scala:121) [scalatra_2.10-2.2.2.jar:2.2.2]
        at skinny.controller.SkinnyController.servletContext(SkinnyController.scala:6) [skinny-framework_2.10-1.0.0-RC6-SNAPSHOT.jar:1.0.0-RC6-SNAPSHOT]
        at org.scalatra.ScalatraFilter$class.routeBasePath(ScalatraFilter.scala:66) [scalatra_2.10-2.2.2.jar:2.2.2]
        at skinny.controller.SkinnyController.routeBasePath(SkinnyController.scala:6) [skinny-framework_2.10-1.0.0-RC6-SNAPSHOT.jar:1.0.0-RC6-SNAPSHOT]
        at org.scalatra.ScalatraBase$$anonfun$7.apply(ScalatraBase.scala:529) ~[scalatra_2.10-2.2.2.jar:2.2.2]
        at org.scalatra.ScalatraBase$$anonfun$7.apply(ScalatraBase.scala:529) ~[scalatra_2.10-2.2.2.jar:2.2.2]
        at org.scalatra.UrlGeneratorSupport$class.url(UrlGenerator.scala:55) ~[scalatra_2.10-2.2.2.jar:2.2.2]
        at org.scalatra.UrlGenerator$.url(UrlGenerator.scala:61) ~[scalatra_2.10-2.2.2.jar:2.2.2]
        at org.scalatra.UrlGeneratorSupport$class.url(UrlGenerator.scala:21) ~[scalatra_2.10-2.2.2.jar:2.2.2]
        at org.scalatra.UrlGenerator$.url(UrlGenerator.scala:61) ~[scalatra_2.10-2.2.2.jar:2.2.2]
        at org.scalatra.scalate.ScalatraRenderContext.url(ScalatraRenderContext.scala:86) ~[scalatra-scalate_2.10-2.2.2.jar:2.2.2]
        at templates.layouts.$_scalate_$default_jade$.$_scalate_$render(default.jade.scala:86) ~[na:na]
        at templates.layouts.$_scalate_$default_jade.render(default.jade.scala:138) ~[na:na]
        at org.fusesource.scalate.layout.DefaultLayoutStrategy.org$fusesource$scalate$layout$DefaultLayoutStrategy$$tryLayout(DefaultLayoutStrategy.scala:77) ~[scalate-core_2.10-1.6.1.jar:1.6.1]
        at org.fusesource.scalate.layout.DefaultLayoutStrategy$$anonfun$1.apply(DefaultLayoutStrategy.scala:59) ~[scalate-core_2.10-1.6.1.jar:1.6.1]
        at org.fusesource.scalate.layout.DefaultLayoutStrategy$$anonfun$1.apply(DefaultLayoutStrategy.scala:59) ~[scalate-core_2.10-1.6.1.jar:1.6.1]
        at scala.collection.LinearSeqOptimized$class.find(LinearSeqOptimized.scala:100) ~[scala-library.jar:0.13.1]
        at scala.collection.immutable.List.find(List.scala:84) ~[scala-library.jar:0.13.1]
        at org.fusesource.scalate.layout.DefaultLayoutStrategy.layout(DefaultLayoutStrategy.scala:59) ~[scalate-core_2.10-1.6.1.jar:1.6.1]
        at org.fusesource.scalate.TemplateEngine$$anonfun$layout$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(TemplateEngine.scala:559) ~[scalate-core_2.10-1.6.1.jar:1.6.1]
        at org.fusesource.scalate.TemplateEngine$$anonfun$layout$1$$anonfun$apply$mcV$sp$1.apply(TemplateEngine.scala:559) ~[scalate-core_2.10-1.6.1.jar:1.6.1]
        at org.fusesource.scalate.TemplateEngine$$anonfun$layout$1$$anonfun$apply$mcV$sp$1.apply(TemplateEngine.scala:559) ~[scalate-core_2.10-1.6.1.jar:1.6.1]
        at org.fusesource.scalate.RenderContext$class.withUri(RenderContext.scala:447) ~[scalate-core_2.10-1.6.1.jar:1.6.1]
        at org.fusesource.scalate.DefaultRenderContext.withUri(DefaultRenderContext.scala:30) ~[scalate-core_2.10-1.6.1.jar:1.6.1]
        at org.fusesource.scalate.TemplateEngine$$anonfun$layout$1.apply$mcV$sp(TemplateEngine.scala:558) ~[scalate-core_2.10-1.6.1.jar:1.6.1]
        at org.fusesource.scalate.TemplateEngine$$anonfun$layout$1.apply(TemplateEngine.scala:555) ~[scalate-core_2.10-1.6.1.jar:1.6.1]
        at org.fusesource.scalate.TemplateEngine$$anonfun$layout$1.apply(TemplateEngine.scala:555) ~[scalate-core_2.10-1.6.1.jar:1.6.1]
        at org.fusesource.scalate.RenderContext$.using(RenderContext.scala:47) ~[scalate-core_2.10-1.6.1.jar:1.6.1]
        at org.fusesource.scalate.TemplateEngine.layout(TemplateEngine.scala:555) ~[scalate-core_2.10-1.6.1.jar:1.6.1]
        at org.fusesource.scalate.TemplateEngine.layout(TemplateEngine.scala:547) ~[scalate-core_2.10-1.6.1.jar:1.6.1]
        at org.fusesource.scalate.TemplateEngine.layout(TemplateEngine.scala:601) ~[scalate-core_2.10-1.6.1.jar:1.6.1]
        at org.scalatra.scalate.ScalateSupport$class.layoutTemplateAs(ScalateSupport.scala:223) [scalatra-scalate_2.10-2.2.2.jar:2.2.2]
        at skinny.controller.SkinnyController.layoutTemplateAs(SkinnyController.scala:6) [skinny-framework_2.10-1.0.0-RC6-SNAPSHOT.jar:1.0.0-RC6-SNAPSHOT]
        at org.scalatra.scalate.ScalateSupport$class.layoutTemplate(ScalateSupport.scala:236) [scalatra-scalate_2.10-2.2.2.jar:2.2.2]
        at skinny.controller.SkinnyController.layoutTemplate(SkinnyController.scala:6) [skinny-framework_2.10-1.0.0-RC6-SNAPSHOT.jar:1.0.0-RC6-SNAPSHOT]
```

**Comment by seratch** [comment]
I tried to write a test suite which simply reproduces this error in Scalatra project, but somehow I couldn't reproduce the situation in Scalatra project. I should investigate more.
