### ISSUE TITLE
Atmosphere buggy with multiple tabs and/or page refreshing

### ISSUE THREAD

**Issue by lightvector** [scalatra/scalatra#542]
I'm running into major problems using atmosphere in Scalatra due to bugs with multiple browser tabs and/or page refreshing in my own projects. It seems like connection state is shared in a weird way such that the server doesn't know that the two tabs are independent connections. And browser page refreshing in the right pattern can cause exceptions to happen within the server. Sometimes, even with a single tab, refreshing the page caused it to no longer receive messages, suggesting that connection state is shared in a weird way across independent reloads of the same page as well.

I was able to reproduce similar problems when running the official atmosphere example:
https://github.com/scalatra/scalatra-website-examples/tree/master/2.4/async/scalatra-atmosphere-example

I followed the instructions - downloaded and compiled the example above and started it with container:start in sbt. I then opened two Chrome tabs and one Firefox tab to the address of the running server (if relevant, this was from a different machine in my local network than the one running the server. That is, I accessed the running example site from an address like http://192.168.1.2:8080/).

(Chrome: Version 45.0.2454.85 m, Firefox: 40.0.3)

I then entered "aaa" into Chrome tab 1, "bbb" into Chrome tab 2, and "ccc" into Firefox tab 1 to set the "username" of each of the chat tabs, and then started chatting between the three browser windows.

Expected result: entering chat into any tab should produce chat for each other tab.
Actual result: "aaa" and "bbb" both outputted chat for "ccc" but NOT for each other. And "ccc" chat ONLY went to "aaa" and NOT "bbb".

I then refreshed the "bbb" page. This resulted in "aaa" no longer receiving any chat and instead "ccc" chat now only went to "bbb".

To stress it a bit more, I then opened a second Firefox tab as well. By flipping around randomly between browsers and tabs refreshing the pages for a while, I eventually got the following exception in the console output for the server:

21:01:00.339 [qtp382381061-87] WARN  o.a.w.DefaultWebSocketProcessor - Failed invoking AtmosphereFramework.doCometSupport()
java.util.NoSuchElementException: key not found: org.scalatra.atmosphere.AtmosphereClientConnection
        at scala.collection.MapLike$class.default(MapLike.scala:228) ~[scala-library-2.11.1.jar:na]
        at org.scalatra.servlet.RichSession.default(RichSession.scala:9) ~[scalatra_2.11-2.3.0.jar:2.3.0]
        at scala.collection.MapLike$class.apply(MapLike.scala:141) ~[scala-library-2.11.1.jar:na]
        at org.scalatra.servlet.RichSession.apply(RichSession.scala:9) ~[scalatra_2.11-2.3.0.jar:2.3.0]
        at org.scalatra.atmosphere.package$$anon$1.client(package.scala:40) ~[scalatra-atmosphere_2.11-2.3.0.jar:2.3.0]
        at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_79]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_79]
        at org.scalatra.atmosphere.ScalatraBroadcaster$$anonfun$1.apply(ScalatraBroadcaster.scala:21) ~[scalatra-atmosphere_2.11-2.3.0.jar:2.3.0]
        at org.scalatra.atmosphere.ScalatraBroadcaster$$anonfun$1.apply(ScalatraBroadcaster.scala:21) ~[scalatra-atmosphere_2.11-2.3.0.jar:2.3.0]
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245) ~[scala-library-2.11.1.jar:na]
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245) ~[scala-library-2.11.1.jar:na]
        at scala.collection.Iterator$class.foreach(Iterator.scala:743) ~[scala-library-2.11.1.jar:na]
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1174) ~[scala-library-2.11.1.jar:na]
        at scala.collection.IterableLike$class.foreach(IterableLike.scala:72) ~[scala-library-2.11.1.jar:na]
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54) ~[scala-library-2.11.1.jar:na]
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:245) ~[scala-library-2.11.1.jar:na]
        at scala.collection.AbstractTraversable.map(Traversable.scala:104) ~[scala-library-2.11.1.jar:na]
        at org.scalatra.atmosphere.ScalatraBroadcaster$class.broadcast(ScalatraBroadcaster.scala:21) ~[scalatra-atmosphere_2.11-2.3.0.jar:2.3.0]
        at org.scalatra.atmosphere.DefaultScalatraBroadcaster.broadcast(DefaultScalatraBroadcaster.scala:8) ~[scalatra-atmosphere_2.11-2.3.0.jar:2.3.0]
        at org.scalatra.atmosphere.AtmosphereClient$class.broadcast(AtmosphereClient.scala:96) ~[scalatra-atmosphere_2.11-2.3.0.jar:2.3.0]
        at org.scalatra.example.atmosphere.ChatController$$anonfun$3$$anon$1.broadcast(ChatController.scala:28) ~[classes/:na]
        at org.scalatra.example.atmosphere.ChatController$$anonfun$3$$anon$1$$anonfun$receive$1.applyOrElse(ChatController.scala:32) ~[classes/:na]
        at org.scalatra.example.atmosphere.ChatController$$anonfun$3$$anon$1$$anonfun$receive$1.applyOrElse(ChatController.scala:29) ~[classes/:na]
        at scala.PartialFunction$Lifted.apply(PartialFunction.scala:218) ~[scala-library-2.11.1.jar:na]
        at scala.PartialFunction$Lifted.apply(PartialFunction.scala:214) ~[scala-library-2.11.1.jar:na]
        at org.scalatra.atmosphere.ScalatraAtmosphereHandler.onRequest(ScalatraAtmosphereHandler.scala:87) ~[scalatra-atmosphere_2.11-2.3.0.jar:2.3.0]
        at org.atmosphere.cpr.AsynchronousProcessor.action(AsynchronousProcessor.java:186) ~[atmosphere-runtime-2.1.5.jar:2.1.5]
        at org.atmosphere.cpr.AsynchronousProcessor.suspended(AsynchronousProcessor.java:98) ~[atmosphere-runtime-2.1.5.jar:2.1.5]
        at org.atmosphere.container.Jetty9AsyncSupportWithWebSocket.service(Jetty9AsyncSupportWithWebSocket.java:179) ~[atmosphere-runtime-2.1.5.jar:2.1.5]
        at org.atmosphere.cpr.AtmosphereFramework.doCometSupport(AtmosphereFramework.java:1809) ~[atmosphere-runtime-2.1.5.jar:2.1.5]
        at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch(DefaultWebSocketProcessor.java:434) [atmosphere-runtime-2.1.5.jar:2.1.5]
        at org.atmosphere.websocket.DefaultWebSocketProcessor.open(DefaultWebSocketProcessor.java:187) [atmosphere-runtime-2.1.5.jar:2.1.5]
        at org.atmosphere.container.Jetty9WebSocketHandler.onWebSocketConnect(Jetty9WebSocketHandler.java:62) [atmosphere-runtime-2.1.5.jar:2.1.5]
        at org.eclipse.jetty.websocket.common.events.JettyListenerEventDriver.onConnect(JettyListenerEventDriver.java:86) [websocket-common-9.1.3.v20140225.jar:9.1.3.v20140225]
        at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.openSession(AbstractEventDriver.java:227) [websocket-common-9.1.3.v20140225.jar:9.1.3.v20140225]
        at org.eclipse.jetty.websocket.common.WebSocketSession.open(WebSocketSession.java:406) [websocket-common-9.1.3.v20140225.jar:9.1.3.v20140225]
        at org.eclipse.jetty.websocket.server.WebSocketServerConnection.onOpen(WebSocketServerConnection.java:63) [websocket-server-9.1.3.v20140225.jar:9.1.3.v20140225]
        at org.eclipse.jetty.server.HttpConnection.completed(HttpConnection.java:318) [jetty-server-9.1.3.v20140225.jar:9.1.3.v20140225]
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:406) [jetty-server-9.1.3.v20140225.jar:9.1.3.v20140225]
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:232) [jetty-server-9.1.3.v20140225.jar:9.1.3.v20140225]
        at org.eclipse.jetty.io.AbstractConnection$1.run(AbstractConnection.java:505) [jetty-io-9.1.3.v20140225.jar:9.1.3.v20140225]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:607) [jetty-util-9.1.3.v20140225.jar:9.1.3.v20140225]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:536) [jetty-util-9.1.3.v20140225.jar:9.1.3.v20140225]
        at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]
21:01:00.341 [qtp382381061-87] WARN  o.a.w.protocol.SimpleHttpProtocol - java.util.NoSuchElementException: key not found: org.scalatra.atmosphere.AtmosphereClientConnection Status 500 Message Server Error
2015-09-27 21:01:00.349:WARN:oac.Jetty9WebSocketHandler:qtp382381061-96: Unhandled Error (closing connection)

**Comment by kounoike** [comment]
I'm checking scalatra-atmosphere behavior for solving #722. This issue maybe related to #722.
I found this issue doesn't occur with scalatra-2.6.x branch and `sbt jetty:start`.
But, I found it occurs with `sbt tomcat:start` (it requires `enablePlugins(JettyPlugin, TomcatPlugin)` in `build.sbt`).

**Steps to Reproduce:**

1. change `enablePlugins` in `build.sbt`. (I also changed ChatController to show uuid when JsonMessage received)
2. run `sbt tomcat:start`
3. open `localhost:8080` in Chrome, open same page in Chrome new tab.
4. login as `ChromeA` and `ChromeB`
5. open `localhost:8080` in Firefox, open same page in new tab.
6. login as `FirefoxA` and `FirefoxB`
7. open `localhost:8080` in InternetExplorer, open same page in new tab.
8. login as `IE_A` and `IE_B`

It shows `tomcat.log` in https://gist.github.com/kounoike/c82c00d56662aa5f99b6b2b4675f8563.

- In each browser, two tabs opened. but only one client opened.
- ChromeA and ChromeB has same uuid.

`jetty.log` (with `jetty:start`) shows:

- Two client opened.
- ChromeA and ChromeB has different uuid.
