### ISSUE TITLE
scalatra-swagger 2.11 build

### ISSUE THREAD

**Issue by rpunjabi** [scalatra/scalatra#546]
We are using 
        <dependency>
            <groupId>org.scalatra</groupId>
            <artifactId>scalatra_2.11</artifactId>
            <version>2.3.1</version>
        </dependency>
        <dependency>
            <groupId>org.scalatra</groupId>
            <artifactId>scalatra-json_2.11</artifactId>
            <version>2.3.1</version>
        </dependency>
        <dependency>
            <groupId>org.scalatra</groupId>
            <artifactId>scalatra-swagger_2.10</artifactId>
            <version>2.3.1</version>
        </dependency>

swagger is not working.  

Trying to see api-docs on swagger-ui results in a 500 on the server.

java.lang.NoSuchMethodError: scala.collection.immutable.$colon$colon.hd$1()Ljava/lang/Object;
    at org.scalatra.swagger.SwaggerBaseBase$$anonfun$initialize$2.apply(SwaggerBase.scala:38)
    at org.scalatra.ScalatraBase$class.org$scalatra$ScalatraBase$$liftAction(ScalatraBase.scala:270)
    at org.scalatra.ScalatraBase$$anonfun$invoke$1.apply(ScalatraBase.scala:265)
    at org.scalatra.ScalatraBase$$anonfun$invoke$1.apply(ScalatraBase.scala:265)
    at org.scalatra.ApiFormats$class.withRouteMultiParams(ApiFormats.scala:182)
    at com.akamai.portal.ace.ResourcesApp.withRouteMultiParams(AceSwagger.scala:6)
    at org.scalatra.ScalatraBase$class.invoke(ScalatraBase.scala:264)
    at com.akamai.portal.ace.ResourcesApp.org$scalatra$json$JsonSupport$$super$invoke(AceSwagger.scala:6)
    at org.scalatra.json.JsonSupport$$anonfun$invoke$1.apply(JsonSupport.scala:88)
    at org.scalatra.json.JsonSupport$$anonfun$invoke$1.apply(JsonSupport.scala:82)
    at org.scalatra.ApiFormats$class.withRouteMultiParams(ApiFormats.scala:182)
    at com.akamai.portal.ace.ResourcesApp.withRouteMultiParams(AceSwagger.scala:6)
    at org.scalatra.json.JsonSupport$class.invoke(JsonSupport.scala:82)
    at com.akamai.portal.ace.ResourcesApp.invoke(AceSwagger.scala:6)
    at org.scalatra.ScalatraBase$$anonfun$runRoutes$1$$anonfun$apply$8.apply(ScalatraBase.scala:240)
    at org.scalatra.ScalatraBase$$anonfun$runRoutes$1$$anonfun$apply$8.apply(ScalatraBase.scala:238)
    at scala.Option.flatMap(Option.scala:171)
    at org.scalatra.ScalatraBase$$anonfun$runRoutes$1.apply(ScalatraBase.scala:238)
    at org.scalatra.ScalatraBase$$anonfun$runRoutes$1.apply(ScalatraBase.scala:237)
    at scala.collection.immutable.Stream.flatMap(Stream.scala:493)

I have a feeling this is because of the version of compiler mismatch between scalatra (2.11) and swagger (2.10)

Is it possible to create a version compiled on 2.11

**Comment by sammyrulez** [comment]
mvnrepository says it exists:
http://mvnrepository.com/artifact/org.scalatra/scalatra-swagger_2.11/2.3.1


maven dependency
<dependency>
	<groupId>org.scalatra</groupId>
	<artifactId>scalatra-swagger_2.11</artifactId>
	<version>2.3.1</version>
</dependency>
