### ISSUE TITLE
Translation of Java future to Scala future logic in Atmosphere integration when broadcasting leads to hung threads in 2.3.x and 2.4.x

### ISSUE THREAD

**Issue by wkozaczuk** [scalatra/scalatra#555]
When calling org.scalatra.atmosphere.AtmosphereClient.broadcast() the applications every so often (we see this happen every 3-4 days in production) gets to the point where all threads calling this method hang with the stack trace like this:

 java.lang.Thread.State: WAITING
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for <48a938aa> (a java.util.concurrent.CountDownLatch$Sync)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:186)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:834)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:994)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1303)
        at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:236)
        at org.atmosphere.cpr.BroadcasterFuture.get(BroadcasterFuture.java:114)
        at org.scalatra.atmosphere.package$$anonfun$pollJavaFutureUntilDoneOrCancelled$3.apply(package.scala:61)
        at scala.util.control.Exception$Catch$$anonfun$withTry$1.apply(Exception.scala:130)
        at scala.util.control.Exception$Catch$$anonfun$withTry$1.apply(Exception.scala:130)
        at scala.util.control.Exception$Catch.apply(Exception.scala:103)
        at scala.util.control.Exception$Catch.withTry(Exception.scala:130)
        at org.scalatra.atmosphere.package$.pollJavaFutureUntilDoneOrCancelled(package.scala:61)
        at org.scalatra.atmosphere.package$.jucFuture2akkaFuture(package.scala:51)
        at org.scalatra.atmosphere.ScalatraBroadcaster$class.broadcast(ScalatraBroadcaster.scala:24)
        at org.scalatra.atmosphere.DefaultScalatraBroadcaster.broadcast(DefaultScalatraBroadcaster.scala:8)
        at org.scalatra.atmosphere.AtmosphereClient$$anonfun$broadcast$1.apply(AtmosphereClient.scala:31)
        at org.scalatra.atmosphere.AtmosphereClient$$anonfun$broadcast$1.apply(AtmosphereClient.scala:31)
        at scala.Option.foreach(Option.scala:257)
        at org.scalatra.atmosphere.AtmosphereClient$.broadcast(AtmosphereClient.scala:31) 
....

I believe there is a bug in this code under org.scalatra.atmosphere.package:

...
48   private[atmosphere] implicit def jucFuture2akkaFuture[T](javaFuture: java.util.concurrent.Future[T])(implicit system: ActorSystem): Future[T] = {
 49     implicit val execContext = system.dispatcher
 50     val promise = Promise[T]()
 51     pollJavaFutureUntilDoneOrCancelled(javaFuture, promise)
 52     promise.future
 53   }
 54
 55   // See here: http://stackoverflow.com/questions/11529145/how-do-i-wrap-a-java-util-concurrent-future-in-an-akka-future
 56   private[atmosphere] def pollJavaFutureUntilDoneOrCancelled[T](javaFuture: java.util.concurrent.Future[T], promise: Promise[T], maybeTimeout: Option[Deadline] = None)(implicit system: ActorSystem) {
 57     implicit val execContext = system.dispatcher
 58     if (maybeTimeout.exists(_.isOverdue())) javaFuture.cancel(true)
 59
 60     if (javaFuture.isDone || javaFuture.isCancelled) {
 61       promise.complete(allCatch withTry { javaFuture.get }).future
 62     } else {
 63       system.scheduler.scheduleOnce(10 milliseconds) {
 64         pollJavaFutureUntilDoneOrCancelled(javaFuture, promise, maybeTimeout)
 65       }
 66     }
 67   }
..

I think this code does not seem to handle the cancelled java future well because based on stacktrace the line of code 61 suggests that javaFuture is either done or cancelled but the org.scalatra.cpr,BroadcasterFuture.get() ends up waiting forever until the underlying latch completes which will never happen I guess if that future was cancelled. This leads to the thread starvation in the underlying thread pool.

We are actually using our own fork of scalatra 2.3.1 - https://github.com/wkozaczuk/scalatra (branch 2.3.1) where we made modification to ScalatraAtmosphereHandler to use AtmosphereResourceSession instead of relying on HttpSession which did not work well (see https://github.com/scalatra/scalatra/issues/416). The bottom line is that we did not change that particular bit of code that I listed above. I believe that this issue applies to both 2.3.* and 2.4.*

Our interim fix (since we have a fork) will be to not to use this translation as we do not need a callback mechanism when futures completes

**Comment by wkozaczuk** [comment]
Also this code ends being buggy because the atmosphere BroadcasterFuture.get() method does not obey the contract of the java.util.concurrent.Future as it should throw cancellationexception and it does not.

**Comment by wkozaczuk** [comment]
Also the Broadcaster.isDone() seems to have a bug. It sets done to true which means it actually mutates the state:

    @Override
    public boolean isDone() {

        if (innerFuture != null) {
            return innerFuture.isDone();
        }

        isDone = true;
        return isDone;
    }

**Comment by wkozaczuk** [comment]
Also here is a bug I reported against atmosphere - https://github.com/Atmosphere/atmosphere/issues/2088

**Comment by wkozaczuk** [comment]
I believe I have fixed the defect described as part of this issue. Also the application that uses my fork of Scalatra 2.3.1 has been running for over the year without any problems in production.

I have essentially changed org/scalatra/atmosphere/AtmosphereClient and related classes and objects in org/scalatra/atmosphere package to no convert Java futures into Scala futures which is buggy partly because of the bug in Atmosphere https://github.com/Atmosphere/atmosphere/issues/2088 (which has been fixed since). So it could be that my fix is no longer necessary. Also in our case we did not need to act upon future completion or failure so not having this ability maybe an issue for some.

Anyway I have not had time nor I have time now to create a pull request for this given my changes are part of 2.3.1 fork and Scalatra's latest release is 2.4.x. Anyway if anybody is interested in cherry-picking my changes or somehow incorporating some of it into the master here is the link to my patch:

https://github.com/wkozaczuk/scalatra/commit/d46572a68efbc2a3de756a2fc6795ef46e0602c8
