### ISSUE TITLE
NPE when trying to read environment type in servlet constructor

### ISSUE THREAD

**Issue by zorba128** [scalatra/scalatra#559]
I've noticed NPE when trying to read out environment type within servlet constructor:

```
class XRuntimeConsoleServlet extends ScalatraServlet {
  println("This throws NPE: " + this.environment)
  get("/env") { "This works fine: " + this.environment }
}
```

I nowhere set environment type - so it should fallback to default "DEVELOPMENT" value.

Exception

```
java.lang.NullPointerException
        at org.scalatra.servlet.ServletBase$$anon$1$initParameters$.get(ServletBase.scala:36)
        at org.scalatra.ScalatraBase$$anonfun$environment$1.apply(ScalatraBase.scala:781) ~[scalatra_2.11-2.4.0.jar:2.4.0]
        at org.scalatra.servlet.ServletBase$$anon$1$initParameters$.get(ServletBase.scala:34)
        at org.scalatra.ScalatraBase$$anonfun$environment$1.apply(ScalatraBase.scala:781) ~[scalatra_2.11-2.4.0.jar:2.4.0]
        at org.scalatra.ScalatraBase$class.initParameter(ScalatraBase.scala:775)
        at scala.Option.orElse(Option.scala:289) ~[scala-library-2.11.7.jar:na]
        at RuntimeUI.initParameter(RuntimeUI.scala:24)
        at org.scalatra.ScalatraBase$class.environment(ScalatraBase.scala:781) ~[scalatra_2.11-2.4.0.jar:2.4.0]
        at org.scalatra.ScalatraBase$$anonfun$environment$1.apply(ScalatraBase.scala:781)
```

Tested on scalatra version 2.4.0.RC3 and scalatra_2.11-2.4.0.

**Comment by poslegm** [comment]
Apparently while application is calling the constructor, servlet config still will not be initialized.

You can accept servlet context explicitly

```
import org.scalatra._
import javax.servlet.ServletContext

class ExampleServlet(context: ServletContext) extends ScalatraServlet {

  println("This not throws NPE: " + context.environment)
  get("/env") {
    "This works fine: " + this.environment
  }

}
```

**Comment by magnolia-k** [comment]
This issue is closed because the answer in the comment seems to have solved the problem.
