### ISSUE TITLE
AtmosphereSpec fail on JDK11

### ISSUE THREAD

**Issue by xuwei-k** [scalatra/scalatra#859]
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Map(Connection -> keep-alive, User-Agent -> Apache-HttpClient/4.5.6 (Java/11), Host -> localhost:49891, Accept-Encoding -> gzip,deflate)
routeBasePath: 
requestPath: /echo
Map(Date -> Sun, 07 Oct 2018 08:56:20 GMT, Content-Type -> text/plain;charset=utf-8, Content-Length -> 7, Server -> Jetty(9.4.6.v20170531))
Map(Origin -> http://localhost:49891, Sec-WebSocket-Key -> 7Mf5P6qAy8JIEJRO79fTMA==, Accept -> */*, Connection -> Upgrade, User-Agent -> wAsync/2.0, Sec-WebSocket-Version -> 13, Host -> localhost:49891, Upgrade -> WebSocket)
routeBasePath: 
requestPath: /test1
Connection Error 500 : Server Error
	at org.atmosphere.wasync.transport.WebSocketTransport.onStatusReceived(WebSocketTransport.java:209)
	at com.ning.http.client.providers.netty.handler.WebSocketProtocol.handle(WebSocketProtocol.java:96)
	at com.ning.http.client.providers.netty.handler.Processor.messageReceived(Processor.java:88)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:459)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:485)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.handler.codec.http.HttpClientCodec.handleUpstream(HttpClientCodec.java:92)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
[info] AtmosphereSpec
[info] To support Atmosphere, Scalatra should
[info]   + allow regular requests
[error]   ! allow one client to connect
[error]    java.io.IOException: Connection Error 500 : Server Error (WebSocketTransport.java:269)
[error] org.atmosphere.wasync.transport.WebSocketTransport.connectFutureException(WebSocketTransport.java:269)
[error] org.atmosphere.wasync.transport.WebSocketTransport.onFailure(WebSocketTransport.java:355)
[error] org.atmosphere.wasync.transport.WebSocketTransport.onThrowable(WebSocketTransport.java:122)
[error] com.ning.http.client.providers.netty.future.NettyResponseFuture.abort(NettyResponseFuture.java:238)
[error] com.ning.http.client.providers.netty.request.NettyRequestSender.abort(NettyRequestSender.java:420)
[error] com.ning.http.client.providers.netty.handler.Processor.exceptionCaught(Processor.java:178)
[error] org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:112)
[error] org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
[error] org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
[error] org.jboss.netty.handler.codec.frame.FrameDecoder.exceptionCaught(FrameDecoder.java:377)
[error] org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:112)
[error] org.jboss.netty.handler.codec.http.HttpClientCodec.handleUpstream(HttpClientCodec.java:92)
[error] org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
[error] org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
[error] org.jboss.netty.channel.Channels.fireExceptionCaught(Channels.java:525)
[error] org.jboss.netty.channel.AbstractChannelSink.exceptionCaught(AbstractChannelSink.java:48)
[error] org.jboss.netty.channel.DefaultChannelPipeline.notifyHandlerException(DefaultChannelPipeline.java:658)
[error] org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:566)
[error] org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
[error] org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
[error] org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:459)
[error] org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536)
[error] org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:485)
[error] org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
[error] org.jboss.netty.handler.codec.http.HttpClientCodec.handleUpstream(HttpClientCodec.java:92)
[error] org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
[error] org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
[error] org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
[error] org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
[error] org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
[error] org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
[error] org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
[error] org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
[error] org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
[error] org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
[error] org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
[error] org.atmosphere.wasync.transport.WebSocketTransport.onStatusReceived(WebSocketTransport.java:209)
[error] com.ning.http.client.providers.netty.handler.WebSocketProtocol.handle(WebSocketProtocol.java:96)
[error] com.ning.http.client.providers.netty.handler.Processor.messageReceived(Processor.java:88)
[error] org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
[error] org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
[error] org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
[error] org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
[error] org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:459)
[error] org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536)
[error] org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:485)
[error] org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
[error] org.jboss.netty.handler.codec.http.HttpClientCodec.handleUpstream(HttpClientCodec.java:92)
[error] org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
[error] org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
[error] org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
[error] org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
[error] org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
[error] org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
[error] org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
[error] org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
[error] org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
[error] org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
[error] org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
[error] CAUSED BY
[error]  org.atmosphere.wasync.transport.TransportNotSupported: null (WebSocketTransport.java:209)
[error] org.atmosphere.wasync.transport.WebSocketTransport.onStatusReceived(WebSocketTransport.java:209)
[error] com.ning.http.client.providers.netty.handler.WebSocketProtocol.handle(WebSocketProtocol.java:96)
[error] com.ning.http.client.providers.netty.handler.Processor.messageReceived(Processor.java:88)
[error] org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
[error] org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
[error] org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
[error] org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
[error] org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:459)
[error] org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536)
[error] org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:485)
[error] org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
[error] org.jboss.netty.handler.codec.http.HttpClientCodec.handleUpstream(HttpClientCodec.java:92)
[error] org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
[error] org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
[error] org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
[error] org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
[error] org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
[error] org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
[error] org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
[error] org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
[error] org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
[error] org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
[error] org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
[info] Total for specification AtmosphereSpec
[info] Finished in 592 ms
[info] 2 examples, 4 expectations, 0 failure, 1 error
[info] ScalaTest
[info] Run completed in 1 second, 538 milliseconds.
[info] Total number of tests run: 0
[info] Suites: completed 0, aborted 0
[info] Tests: succeeded 0, failed 0, canceled 0, ignored 0, pending 0
[info] No tests were executed.
[error] Error: Total 2, Failed 0, Errors 1, Passed 1
[error] Error during tests:
[error] 	org.scalatra.atmosphere.AtmosphereSpec
[error] (Test / test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 3 s, completed Oct 7, 2018, 5:56:21 PM
```

**Comment by xuwei-k** [comment]
🤔 https://github.com/xuwei-k/scalatra/commit/2093ccc82fdf219be16c30f7af7c589ebdcba5b0

**Comment by magnolia-k** [comment]
Java 11 introduces a method named isBlank with the same name as Scalatra provides to java.lang.String, because that has priority.

[https://download.java.net/java/early_access/jdk11/docs/api/java.base/java/lang/String.html#isBlank()](https://download.java.net/java/early_access/jdk11/docs/api/java.base/java/lang/String.html#isBlank())

Since isBlank provided by java.lang.String can not handle null, an exception is thrown.

It seems better to deprecate isBlank provided by Scalatra.

**Comment by magnolia-k** [comment]
Considering compatibility with versions prior to Java 11, it seems reasonable to replace it with org.apache.commons.lang3.StringUtils.
(As it is already used elsewhere in Scalatra)

**Comment by xuwei-k** [comment]
https://github.com/scalatra/scalatra/commit/8df4f67d0c4a806236135581ede44cbd2e63fc74
